/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko_handphone.view;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import toko_handphone.DBConnection;
import toko_handphone.entity.Barang;
import toko_handphone.model.BarangModel;
import java.sql.ResultSet;

public class BarangForm extends javax.swing.JDialog {

    /**
     * Creates new form BarangForm
     */
    
    private Connection connection;
    private Barang barang;
    private BarangModel barangModel;
    private BarangData barangData;
    
    public BarangForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        connection = DBConnection.newInstant();
        barang = new Barang();
        barangModel = new BarangModel (connection);
        barangModel = new BarangModel(connection);
        barangData = new BarangData(parent, true);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textImei = new javax.swing.JTextField();
        textMerkHp = new javax.swing.JTextField();
        textStorage = new javax.swing.JTextField();
        buttonBaru = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonData = new javax.swing.JButton();
        textHarga = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BarangForm");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Imei");

        jLabel2.setText("Nama Handphone");

        jLabel3.setText("Storage");

        jLabel4.setText("Harga");

        textImei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textImeiActionPerformed(evt);
            }
        });

        buttonBaru.setText("BARU");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });

        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonUbah.setText("UBAH");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonData.setText("DATA");
        buttonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataActionPerformed(evt);
            }
        });

        textHarga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        textHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textHarga.setValue(0);
        textHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textImei)
                            .addComponent(textStorage)
                            .addComponent(textMerkHp)
                            .addComponent(textHarga)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(buttonBaru)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonUbah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(buttonData)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textImei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMerkHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBaru)
                    .addComponent(buttonTambah)
                    .addComponent(buttonUbah)
                    .addComponent(buttonHapus)
                    .addComponent(buttonData))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        textHarga.getAccessibleContext().setAccessibleParent(textHarga);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        barang.setImei(textImei.getText());
        barang.setMerk_hp(textMerkHp.getText());
        barang.setStorage(textStorage.getText());

        try {
            barang.setHarga(Integer.valueOf(String.valueOf(textHarga.getValue())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga tidak valid", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Simpan data ke database
            connection.setAutoCommit(false);
            barangModel.insert(barang);
            connection.commit();

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);

            // Reset form untuk entri baru
            buttonBaruActionPerformed(evt);
        } catch (SQLException ex) {
            // Rollback jika terjadi kesalahan
            try {
                connection.rollback();
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan: " + ex.getMessage(), "KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
        textImei.setText (null);
        textMerkHp.setText (null);
        textStorage.setText (null);
        textHarga.setValue(0);
        textImei.requestFocus();
        
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed

    // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin menghapus barang dengan kode " + textImei.getText() + "?",
        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

    // Jika pengguna memilih "Yes"
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Set kode barang yang akan dihapus
            barang.setImei(textImei.getText());

            // Hapus barang dari database
            connection.setAutoCommit(false);
            barangModel.delete(barang);
            connection.commit();

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Barang berhasil dihapus", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            // Tampilkan pesan gagal
            JOptionPane.showMessageDialog(this, "Barang gagal dihapus", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void textHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textHargaActionPerformed

    private void textImeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textImeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textImeiActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
     
    // Mengambil data dari form
    barang.setImei(textImei.getText());
    barang.setMerk_hp(textMerkHp.getText());
    barang.setStorage(textStorage.getText());

    // Ambil harga satuan dari form
    try {
        barang.setHarga(Integer.valueOf(String.valueOf(textHarga.getValue())));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harga valid", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Pastikan kode barang tidak kosong
    if (barang.getImei().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Kode barang tidak boleh kosong", "KESALAHAN", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Set auto commit ke false
        connection.setAutoCommit(false);

        // Update data barang di database
        barangModel.update(barang);

        // Commit perubahan
        connection.commit();

        // Tampilkan pesan berhasil
        JOptionPane.showMessageDialog(this, "Data barang berhasil diubah", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
        try {
            // Rollback jika terjadi kesalahan
            connection.rollback();
        } catch (SQLException rollbackEx) {
            rollbackEx.printStackTrace();
        }

        // Tampilkan pesan gagal
        JOptionPane.showMessageDialog(this, "Data barang gagal diubah: " + ex.getMessage(), "KESALAHAN", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }

    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataActionPerformed
            // TODO add your handling code here:
            // TODO add your handling code here:
       barangData.show();
    barang = barangData.getSelectionRow();

    if (barang != null) {
        textImei.setText(barang.getImei());
        textMerkHp.setText(barang.getMerk_hp());
        textStorage.setText(barang.getStorage());
        textHarga.setValue(barang.getHarga());
    }
        
    
    }//GEN-LAST:event_buttonDataActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BarangForm dialog = new BarangForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaru;
    private javax.swing.JButton buttonData;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField textHarga;
    private javax.swing.JTextField textImei;
    private javax.swing.JTextField textMerkHp;
    private javax.swing.JTextField textStorage;
    // End of variables declaration//GEN-END:variables
}
