/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toko_handphone.view;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Vector;
import toko_handphone.DBConnection;
import toko_handphone.entity.Barang;
import toko_handphone.model.BarangModel;
import toko_handphone.entity.Pelanggan;
import toko_handphone.model.PelangganModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;


public class MainMenu extends javax.swing.JFrame {
    
    private BarangForm barangForm;
    private PelangganForm pelangganForm;
    private PenjualanForm penjualanForm;
    private Connection koneksi;
    private BarangModel barangModel;
    private PelangganModel pelangganModel;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        barangForm = new BarangForm(this, true);
        barangForm.setLocationRelativeTo(this);
        
        pelangganForm = new PelangganForm(this, true);
        pelangganForm.setLocationRelativeTo(this);
        
        penjualanForm = new PenjualanForm();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        koneksi = DBConnection.newInstant();
        barangModel = new BarangModel(koneksi);
        pelangganModel = new PelangganModel(koneksi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPenjualan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBarang = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        DataPelanggan = new javax.swing.JMenuItem();
        DataBarang = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI PENJUALAN");
        setName("MainMenu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jMenu1.setText("Transaksi");
        jMenu1.setName(""); // NOI18N

        menuPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(menuPenjualan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuBarang);

        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(menuPelanggan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        DataPelanggan.setText("Data Pelanggan");
        DataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(DataPelanggan);

        DataBarang.setText("Data Barang");
        DataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBarangActionPerformed(evt);
            }
        });
        jMenu3.add(DataBarang);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        try{
            penjualanForm.show();
            penjualanForm.setSelected(true);
        }catch(PropertyVetoException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jDesktopPane1.add(penjualanForm);
    }//GEN-LAST:event_formWindowOpened

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        // TODO add your handling code here:
        barangForm.show();
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        // TODO add your handling code here:
        pelangganForm.show();
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void DataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBarangActionPerformed
        HashMap parameter = new HashMap();
        Vector<HashMap> data = new Vector<HashMap>();
        int no = 0;
        for (Barang barang : barangModel.getData()){
            HashMap row = new HashMap();
            row.put("imei", barang.getImei());
            row.put("merk_hp", barang.getMerk_hp());
            row.put("storage", barang.getStorage());
            row.put("harga", barang.getHarga());
            row.put("no", ++no);
            data.add(row);
            try{
                JRDataSource dataSource = new JRBeanCollectionDataSource(data);
                InputStream file = getClass().getResourceAsStream("BarangDataLaporan.jasper");
                JasperPrint jasperPrint = JasperFillManager.fillReport(file, parameter, dataSource);                          
                JasperViewer.viewReport(jasperPrint, false);
            }catch(JRException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_DataBarangActionPerformed

    private void DataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPelangganActionPerformed
        HashMap parameter = new HashMap();
        Vector<HashMap> data = new Vector<HashMap>();
        int no = 0;
        for (Pelanggan user : pelangganModel.getData()){
            HashMap row = new HashMap();
            row.put("kode", user.getKode());
            row.put("nama", user.getNama());
            row.put("alamat", user.getAlamat());
            row.put("telepon", user.getTelepon());
            row.put("no", ++no);
            data.add(row);

            try{
                JRDataSource dataSource = new JRBeanCollectionDataSource(data);
                InputStream file = getClass().getResourceAsStream("LaporanPelanggan.jasper");
                JasperPrint jasperPrint = JasperFillManager.fillReport(file, parameter, dataSource);                          
                JasperViewer.viewReport(jasperPrint, false);
                
            }catch(JRException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_DataPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataBarang;
    private javax.swing.JMenuItem DataPelanggan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPenjualan;
    // End of variables declaration//GEN-END:variables
}
